# Header
menu:
  Home: /
  TeamSpeak: ts3server://ts3.poweredbyjeff.com
  Minecraft: /minecraft
  Map: http://minecraft.poweredbyjeff.com
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-43838521-1
favicon: /favicon.png