# Header
menu:
  Home: /
  Discord: https://discord.gg/vet2u5J
  Résumé: /jeff-ferrari-resume

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-43838521-1
favicon: /favicon.png