# Header
menu:
  GitHub: https://github.com/tuxillator
  LinkedIn: http://www.linkedin.com/in/jjferrari
  #Archive: /archives/

# Content
excerpt_link: Read More...
fancybox: true

# Miscellaneous
google_analytics: UA-43838521-1
favicon: /favicon.png
